name: proyecto_integrador_V

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - Crear entorno virtual
        run: python -m venv venv
      - name: paso2 - Activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - Actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Ejecutar Script
        run: python src/PIV_Oro/static/ejecucion.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: generación informe
          commit_user_name: Natalia Rojas [GitHub Actions]
          commit_user_email: natalia.rojas@est.iudigital.edu.co
          commit_author: Natalia Rojas <natalia.rojas@est.iudigital.edu.co>
